apiVersion: v1
kind: Service
metadata:
  name: service-posts
spec:
  selector:
    app: service-posts
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-posts
spec:
  selector:
    matchLabels:
      app: service-posts
  replicas: 1
  template:
    metadata:
      labels:
        app: service-posts
    spec:
      containers:
        - name: server
          image: linkdew/service-posts:latest
          ports:
            - name: http
              containerPort: 8081

---
